# main 브랜치에 push가 발생할 때만 실행
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 깃허브 저장소 체크아웃 (fetch-depth: 0은 전체 커밋 히스토리를 가져옴)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # JDK 17 설정 (Spring Boot 3.x 기준)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      # semantic-release는 Node.js 기반이므로 Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
          
      # semantic-release 관련 npm 패키지 설치
      # @semantic-release/git: 깃 커밋/태그 자동화
      # @semantic-release/changelog: CHANGELOG.md 자동 생성
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog
        
      # Gradle 캐시 설정으로 빌드 속도 향상
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          
      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
